server:
  port: 8083

spring:
  application:
    name: web_mng_authentication

eureka:
  client:
    register-with-eureka: true
    disable-delta: true
    service-url:
      defaultZone: http://localhost:8761/eureka
